import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

interface Props {
  children: JSX.Element | JSX.Element[];
}

const PageLayout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.title}>
        <h1>Poke Api</h1>
      </header>

      <main>{children}</main>
    </>
  );
};

export default PageLayout;
