import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Pokemons } from "../pages/pokedex";
import { BiSearchAlt2 } from "react-icons/bi";

const PokemonsLayout = (pokemon: Pokemons) => {
  function getType(id: number): string[] {
    const type = pokemon.types.find((type) => type.id === id);
    if (typeof type !== "undefined") {
      const typeColor = type?.types;
      return typeColor;
    } else {
      throw new Error("Type not found");
    }
  }

  const bgColors: { [key: string]: string } = {
    grass: "bg-grass",
    poison: "bg-poison",
    fire: "bg-fire",
    flying: "bg-flying",
    water: "bg-water",
    bug: "bg-bug",
    normal: "bg-normal",
    electric: "bg-electric",
    ground: "bg-ground",
    fairy: "bg-fairy",
    fighting: "bg-fighting",
    psychic: "bg-psychic",
    rock: "bg-rock",
    ghost: "bg-ghost",
    ice: "bg-ice",
    dragon: "bg-dragon",
    steel: "bg-steel",
    dark: "bg-dark",
  };

  const pokemonList = pokemon.pokemon;

  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-800">
        <h1 className="flex justify-center pt-10 mb-5 font-bold font-luckiest text-6xl text-yellow-300 title ">
          Pokédex
        </h1>
        <div className="flex flex-row justify-center items-center bg-gray-800">
          <input
            className="w-1/2 mb-5 bg-gray-800 border-2 border-yellow-300 rounded-md text-yellow-300 focus:outline-none focus:ring-2 focus:ring-yellow-300 focus:border-transparent"
            type="text"
            placeholder="Search for a Pokémon"
          />
          <BiSearchAlt2 className="text-xl -mx-7 mb-5 text-yellow-300" />
        </div>
        <div className="flex flex-wrap justify-center mx-10 bg-bg-main">
          {pokemonList.map((pokemon: { name: string; url: string }) => {
            const pokemonId: number = parseInt(pokemon.url.split("/")[6]);
            const imageUrl: string = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${pokemonId}.png`;
            return (
              <Link key={pokemon.name} href={`/pokedex/${pokemon.name}`}>
                <div
                  key={pokemon.name}
                  className={`flex flex-col justify-center items-center pokemon-card hover:scale-105 bg-
                  ${bgColors[getType(pokemonId)[0]]}
                  `}
                >
                  <div className="mb-1">
                    <Image
                      src={imageUrl}
                      alt={pokemon.name}
                      width={100}
                      height={100}
                    />
                  </div>
                  <div className="circle"></div>
                  <h5 className="poke-id">#{pokemonId}</h5>
                  <h5 className="poke-name">
                    {pokemon.name[0].toUpperCase() + pokemon.name.slice(1)}
                  </h5>
                  <span>
                    <h5 className="poke-type capitalize">
                      {getType(pokemonId)
                        ?.join(" / ")
                        .replace(/\b\w/g, (ch) => ch.toUpperCase())}
                    </h5>
                  </span>
                </div>
              </Link>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default PokemonsLayout;
