import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import PageLayout from "../components/PageLayout";

const Home: NextPage = () => {
  return (
    <>
      <div className="flex flex-col justify-center items-center min-h-screen bg-gray-800">
        <PageLayout>
          <Head>
            <title>Poke NextJS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Link href="/pokemon">
            <button className="text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
              Click me to discover the best pokemon generation!
            </button>
          </Link>
        </PageLayout>
      </div>
    </>
  );
};

export default Home;
