import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import PageLayout from "../components/PageLayout";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.main}>
        <PageLayout>
          <Head>
            <title>Poke NextJS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Link href="/pokemon">
            <button>Click me to discover the best pokemon generation!</button>
          </Link>
        </PageLayout>
      </div>
    </>
  );
};

export default Home;
