import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

type pokemons = {
  pokemons: [
    {
      name: string;
      url: string;
    }
  ];
};

const Pokemon = ({ pokemons }: pokemons) => {
  return (
    <>
      <Head>
        <title>Pokemon API NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-800">
        <h1 className="flex justify-center pt-10 text-3xl font-bold mb-5 text-sky-500">
          Pokédex
        </h1>
        <div className="flex flex-wrap justify-center mx-10 bg-bg-main">
          {pokemons.map((pokemon: { name: string; url: string }) => {
            const pokemonId = pokemon.url.split("/")[6];
            const imageUrl = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${pokemonId}.png`;
            return (
              <div
                key={pokemon.name}
                className="flex flex-col justify-center items-center pokemon-card"
              >
                <div className="circle"></div>
                <h5 className="poke-id">{pokemonId}</h5>
                <h5 className="poke-name">
                  {pokemon.name[0].toUpperCase() + pokemon.name.slice(1)}
                </h5>
                <div>
                  <Image
                    src={imageUrl}
                    alt={pokemon.name}
                    width={100}
                    height={100}
                  />
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
};

export async function getServerSideProps() {
  const res = await fetch(
    "https://pokeapi.co/api/v2/pokemon?limit=151&offset=0"
  );
  const data = await res.json();

  return {
    props: {
      pokemons: data.results,
    },
  };
}

export default Pokemon;
