import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

type pokemons = {
  pokemons: [
    {
      name: string;
      url: string;
    }
  ];
};

const Pokemon = ({ pokemons }: pokemons) => {
  return (
    <>
      <Head>
        <title>Pokemon API NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <h1 className={styles.title}>Poke API</h1>
      </Link>
      <div className={`${styles.grid} ${styles.container}`}>
        {pokemons.map((pokemon: { name: string; url: string }) => {
          const pokemonId = pokemon.url.split("/")[6];
          const imageUrl = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemonId}.png`;
          return (
            <div key={pokemon.name} className={styles.card}>
              <p className={styles.title}>
                {pokemon.name[0].toUpperCase() + pokemon.name.slice(1)}
              </p>
              <div className={styles.title}>
                <Image
                  src={imageUrl}
                  alt={pokemon.name}
                  width={100}
                  height={100}
                />
              </div>
            </div>
          );
        })}
      </div>
    </>
  );
};

export async function getServerSideProps() {
  const res = await fetch(
    "https://pokeapi.co/api/v2/pokemon?limit=151&offset=0"
  );
  const data = await res.json();

  return {
    props: {
      pokemons: data.results,
    },
  };
}

export default Pokemon;
