import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import { Query } from "../interfaces/interfaces";
import { pokemon, pokemonList } from "../interfaces/interfaces";

export default function Component({
  query,
  pokemonList,
}: {
  query: string;
  pokemonList: pokemonList;
}) {
  const [searchResults, setSearchResults] = useState<pokemon[]>([]);

  useEffect(() => {
    if (query.length > 0) {
      const results = pokemonList.filter((pokemon: pokemon) =>
        pokemon.name.toLowerCase().includes(query.toLowerCase())
      );
      setSearchResults(results);
    } else {
      setSearchResults([]);
    }
  }, [query]);

  return (
    <>
      <Head>
        <title>Pokemon search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row justify-start items-center bg-gray-800">
        <Link href={"/pokedex"}>
          <a>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className={`w-9 h-9 text-gray-800 bg-slate-100 hover:bg-yellow-300 mt-5 ml-5 rounded-full  p-2`}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3"
              />
            </svg>
          </a>
        </Link>
      </div>
      <div className="bg-gray-800 h-screen">
        <h1 className="flex justify-center pt-10 mb-10 font-bold text-6xl text-yellow-300 title">
          Search results for "{query}"
        </h1>
        <div className="flex flex-wrap justify-center bg-gray-800">
          {searchResults.length > 0 ? (
            searchResults.map((pokemon: pokemon) => (
              <div
                key={pokemon.name}
                className="flex flex-col items-center justify-center font-bold p-5 bg-gray-700 rounded-lg m-2 hover:bg-yellow-400 hover:text-gray-800"
              >
                <Link href={`/pokedex/${pokemon.name}`}>
                  <a>
                    <div className="flex flex-col items-center justify-center w-40 h-40 bg-gray-800 rounded-full">
                      <Image
                        src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${
                          pokemon.url.split("/")[6]
                        }.png`}
                        alt={pokemon.name}
                        priority
                        width={100}
                        height={100}
                      />
                      <h1 className="text-white text-center capitalize">
                        {pokemon.name}
                      </h1>
                    </div>
                  </a>
                </Link>
              </div>
            ))
          ) : (
            <h1 className="text-white text-center">No results founds</h1>
          )}
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps(context: { query: Query }) {
  const { query } = context;
  const q = query.query;

  const request = await fetch(
    "https://pokeapi.co/api/v2/pokemon?limit=151&offset=0"
  );
  const response = await request.json();

  return {
    props: {
      query: q,
      pokemonList: response.results,
    },
  };
}
