import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useEffect, useState } from "react";

export default function Component({ query, pokemonList }: any) {
  const [searchResults, setSearchResults] = useState([]);

  useEffect(() => {
    if (query.length > 0) {
      const results = pokemonList.filter((pokemon: any) =>
        pokemon.name.toLowerCase().includes(query.toLowerCase())
      );
      setSearchResults(results);
    } else {
      setSearchResults([]);
    }
  }, [query]);

  return (
    <>
      <Head>
        <title>Pokemon search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-800 h-screen">
        <h1 className="flex justify-center pt-10 mb-5 font-bold text-6xl text-yellow-300 title">
          Search for "{query}"
        </h1>
        <div className="flex flex-wrap justify-center bg-gray-800">
          {searchResults.length > 0 ? (
            searchResults.map((pokemon: any) => (
              <div
                key={pokemon.name}
                className="flex flex-col items-center justify-center font-bold p-5 bg-gray-700 rounded-lg m-2"
              >
                <Link href={`/pokedex/${pokemon.name}`}>
                  <a>
                    <div className="flex flex-col items-center justify-center w-40 h-40 bg-gray-800 rounded-full">
                      <Image
                        src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${
                          pokemon.url.split("/")[6]
                        }.png`}
                        alt={pokemon.name}
                        width={100}
                        height={100}
                      />
                      <h1 className="text-white text-center capitalize">
                        {pokemon.name}
                      </h1>
                    </div>
                  </a>
                </Link>
              </div>
            ))
          ) : (
            <h1 className="text-white text-center">
              No results founds for "{query}"
            </h1>
          )}
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const { query } = context;
  const q = query.query;

  const request = await fetch(
    "https://pokeapi.co/api/v2/pokemon?limit=151&offset=0"
  );
  const response = await request.json();

  // const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${q}`);
  // const results = await res.json();
  return {
    props: {
      //results,
      query: q,
      pokemonList: response.results,
    },
  };
}
